//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotnikov_PR_21_102_DocumentManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_cases
    {
        public test_cases()
        {
            this.test_case_results = new HashSet<test_case_results>();
        }
    
        public int id_test_case { get; set; }
        public int id_project { get; set; }
        public short priority { get; set; }
        public string linked_requirement { get; set; }
        public string name { get; set; }
        public string preconditions { get; set; }
        public string estimated_result { get; set; }
        public string postcondition { get; set; }
        public string id_in_project { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual ICollection<test_case_results> test_case_results { get; set; }
    }
}
