//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotnikov_PR_21_102_DocumentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public customers()
        {
            this.projects = new HashSet<projects>();
        }
    
        public int id_customer { get; set; }
        public string customer_name { get; set; }
        public string customer_sirname { get; set; }
        public string customer_lastname { get; set; }
        public string company_name { get; set; }
        public string comment_from_manager { get; set; }
    
        public virtual ICollection<projects> projects { get; set; }
    }
}
