//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotnikov_PR_21_102_DocumentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public posts()
        {
            this.workers = new HashSet<workers>();
        }
    
        public int id_post { get; set; }
        public string postname { get; set; }
    
        public virtual ICollection<workers> workers { get; set; }
    }
}
