//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotnikov_PR_21_102_DocumentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.workers = new HashSet<workers>();
        }
    
        public int id_role { get; set; }
        public string rolename { get; set; }
    
        public virtual ICollection<workers> workers { get; set; }


        public override string ToString()
        {
            return rolename;
        }
    }
}
