//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotnikov_PR_21_102_DocumentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public workers()
        {
            this.files = new HashSet<files>();
            this.project_workers = new HashSet<project_workers>();
            this.test_case_results = new HashSet<test_case_results>();
        }
    
        public int id_worker { get; set; }
        public int id_post { get; set; }
        public int id_role { get; set; }
        public string name { get; set; }
        public string sirname { get; set; }
        public string lastname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contract { get; set; }
        public Nullable<decimal> approximate_salary { get; set; }
    
        public virtual ICollection<files> files { get; set; }
        public virtual posts posts { get; set; }
        public virtual ICollection<project_workers> project_workers { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<test_case_results> test_case_results { get; set; }

        public override string ToString()
        {
            string patr;
            if (lastname != null)
                patr = lastname;
            else
                patr = "";
            return $"{posts.postname} | {name} {sirname} {patr} | {email}";
        }
    }
}
